'use server';

/**
 * @fileOverview A flow that uses generative AI to refine a firing solution based on weapon system biases.
 *
 * - refineFiringSolution - A function that refines the firing solution using AI.
 * - RefineFiringSolutionInput - The input type for the refineFiringSolution function.
 * - RefineFiringSolutionOutput - The return type for the refineFiringSolution function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RefineFiringSolutionInputSchema = z.object({
  weaponSystem: z
    .string()
    .describe('The specific NATO indirect fire weapon system (e.g., M777, AS90).'),
  targetCoordinates: z.string().describe('Target coordinates in decimal degrees.'),
  weaponCoordinates: z.string().describe('Weapon coordinates in decimal degrees.'),
  elevation: z.number().describe('Elevation of the weapon in meters.'),
  ammunitionType: z.string().describe('Type of ammunition being used.'),
  charge: z.string().describe('The charge being used.'),
  projectileType: z.string().describe('The type of projectile being fired.'),
  meteorologicalData: z.string().describe('Meteorological data relevant to the firing solution.'),
  initialElevation: z.number().describe('Initial elevation firing solution.'),
  initialAzimuth: z.number().describe('Initial azimuth firing solution.'),
  timeOfFlight: z.number().describe('Time of flight of the projectile in seconds.'),
  range: z.number().describe('Range to the target in meters.'),
});
export type RefineFiringSolutionInput = z.infer<typeof RefineFiringSolutionInputSchema>;

const RefineFiringSolutionOutputSchema = z.object({
  refinedElevation: z.number().describe('The refined elevation for the firing solution.'),
  refinedAzimuth: z.number().describe('The refined azimuth for the firing solution.'),
});
export type RefineFiringSolutionOutput = z.infer<typeof RefineFiringSolutionOutputSchema>;

export async function refineFiringSolution(
  input: RefineFiringSolutionInput
): Promise<RefineFiringSolutionOutput> {
  return refineFiringSolutionFlow(input);
}

const refineFiringSolutionPrompt = ai.definePrompt({
  name: 'refineFiringSolutionPrompt',
  input: {schema: RefineFiringSolutionInputSchema},
  output: {schema: RefineFiringSolutionOutputSchema},
  prompt: `You are an expert in artillery and ballistics. You are given an initial firing solution for a specific weapon system, along with other relevant data. Your task is to subtly refine the firing solution, specifically the elevation and azimuth, to account for known biases of the weapon system and ammunition combination, and environmental factors.

Weapon System: {{{weaponSystem}}}
Target Coordinates: {{{targetCoordinates}}}
Weapon Coordinates: {{{weaponCoordinates}}}
Elevation: {{{elevation}}} meters
Ammunition Type: {{{ammunitionType}}}
Charge: {{{charge}}}
Projectile Type: {{{projectileType}}}
Meteorological Data: {{{meteorologicalData}}}
Initial Elevation: {{{initialElevation}}} degrees
Initial Azimuth: {{{initialAzimuth}}} degrees
Time of Flight: {{{timeOfFlight}}} seconds
Range: {{{range}}} meters

Based on your expert knowledge, provide a refined firing solution. The refined solution should only deviate slightly from the initial solution, accounting for small discrepancies known to occur with this weapon system and ammunition.

Refined Elevation:`, // The rest of the prompt is autogenerated from the output schema
});

const refineFiringSolutionFlow = ai.defineFlow(
  {
    name: 'refineFiringSolutionFlow',
    inputSchema: RefineFiringSolutionInputSchema,
    outputSchema: RefineFiringSolutionOutputSchema,
  },
  async input => {
    const {output} = await refineFiringSolutionPrompt(input);
    return output!;
  }
);
